language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      sudo: required
    - os: osx
      osx_image: xcode8.3

# The 'build' task runs most things, including test, check, & static analysis
install: true
script: ./gradlew -u -i -q -S build jacocoAggregateReport coveralls

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.gradle/
