language: java
jdk: oraclejdk8
sudo: false

# The 'build' task runs most things, including test, check, & static analysis
install: true
script: ./gradlew -u -i -q -S build jacocoAggregateReport coveralls

cache:
  directories:
    - $HOME/.gradle/
