version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  # prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - SET PATH=%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - echo %PATH%
  - gradlew.bat --version
build_script:
  - gradlew.bat -u -i install
test_script:
  - gradlew.bat -u -i -S check
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
